#!/bin/bash

# convert board.txt content in variables :
#
# uno.name=Arduino Uno
# uno.upload.protocol=arduino
# uno.upload.maximum_size=32256
# uno.upload.speed=115200
# uno.build.mcu=atmega328p
# uno.build.f_cpu=16000000L
# uno.build.core=arduino
# uno.build.variant=standard
#
# =>
#
# CONFIG_UNO_UPLOAD_PROTOCOL=arduino
# ...

HERE=$(cd $(dirname $0) ; /bin/pwd)
MAIN_DIR=$(dirname $HERE)

INPUT=$MAIN_DIR/src/boards.txt
VERSION_FILE=$MAIN_DIR/src/version.txt
OUTPUT=$MAIN_DIR/target/boards.config

echo "## file generated by $0"

echo "CORE_VERSION := $(cat $VERSION_FILE)"
targets=$( grep -e \.name= $INPUT | cut -d . -f 1 )
echo "TARGETS := " $targets

grep -e \.name= -e \.upload\..*= -e build\..*= $INPUT \
| tr '=' ' ' \
| while read name value ; do
	echo "CONFIG_TARGET_$(echo $name | tr 'a-z.' 'A-Z_') := $value"
done

cat <<EOF

BOARD_CONFIGS=OK
## end of generated file
EOF

