#!/bin/bash

# convert board.txt content in variables :
#
# uno.name=Arduino Uno
# uno.upload.protocol=arduino
# uno.upload.maximum_size=32256
# uno.upload.speed=115200
# uno.build.mcu=atmega328p
# uno.build.f_cpu=16000000L
# uno.build.core=arduino
# uno.build.variant=standard
#
# =>
#
# CONFIG_UNO_UPLOAD_PROTOCOL=arduino
# ...

# + hardcoded choice for multi cpu platforms like mega :
# diecimila.menu.cpu.atmega328.build.mcu=atmega328p
# nano.menu.cpu.atmega328.build.mcu=atmega328p
# mega.menu.cpu.atmega2560.build.mcu=atmega2560
# mini.menu.cpu.atmega328.build.mcu=atmega328p
# bt.menu.cpu.atmega328.build.mcu=atmega328p
# lilypad.menu.cpu.atmega328.build.mcu=atmega328p
# pro.menu.cpu.16MHzatmega328.build.mcu=atmega328p
# atmegang.menu.cpu.atmega168.build.mcu=atmega168

HERE=$(cd $(dirname $0) ; /bin/pwd)
MAIN_DIR=$(dirname $HERE)

INPUT=$MAIN_DIR/src/boards/*.txt
VERSION_FILE=$MAIN_DIR/src/version.txt
OUTPUT=$MAIN_DIR/target/boards.config

echo "## file generated by $0"

echo "CORE_VERSION := $(cat $VERSION_FILE)"
targets=$( grep -h -e \.name= $INPUT | cut -d . -f 1 )
echo "TARGETS := " $targets

grep -h -e \.name= -e \.upload\..*= -e build\..*= $INPUT \
| sed \
  -e 's/=\(.*\):.*/=\1/' \
  -e s/diecimila.menu.cpu.atmega328/diecimila/ \
  -e s/nano.menu.cpu.atmega328/nano/ \
  -e s/mega.menu.cpu.atmega2560/mega/ \
  -e s/mini.menu.cpu.atmega328/mini/ \
  -e s/bt.menu.cpu.atmega328/bt/ \
  -e s/lilypad.menu.cpu.atmega328/lilypad/ \
  -e s/pro.menu.cpu.16MHzatmega328/pro/ \
  -e s/atmegang.menu.cpu.atmega168/atmegang/ \
| tr '=' ' ' \
| while read name value ; do
	echo "CONFIG_TARGET_$(echo $name | tr 'a-z.' 'A-Z_') := $value"
done

cat <<EOF

BOARD_CONFIGS=OK
## end of generated file
EOF

